/**
 * W3: woocommerce.js's emit() (PLAN-1.11.1-v2 KC7, §9 TR3/TR8). Runs the REAL
 * assets/js/trackwp.js AND assets/js/woocommerce.js together in the W0 vm
 * sandbox, fed with a REAL TrackWP_WooCommerce::build_config() capture
 * (tests/fixtures/woo/datalayer-config.json, generated by
 * tests/test-woocommerce-1-11-1-events.php test_generate_js_fixture() --
 * run the PHP suite at least once before this file, or the fixture will be
 * missing/stale).
 *
 * remove_from_cart was cut from 1.11.1 scope by the coordinator
 * (2026-09-29) and is not covered here.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import path from 'node:path';
import { createSandbox, PLUGIN_ROOT } from './helpers/sandbox.mjs';

const REST = 'https://example.org/wp-json/';
const FIXTURE = path.join(PLUGIN_ROOT, 'tests', 'fixtures', 'woo', 'datalayer-config.json');

if (!fs.existsSync(FIXTURE)) {
    throw new Error(
        `Missing producer fixture ${FIXTURE}. Run the PHP suite first: ` +
        `docker compose -f tests/docker/compose.yml run --rm phpunit vendor-dev/bin/phpunit --filter TrackWP_WooCommerce_1111_Events_Test`
    );
}
const FIXTURE_DATA = JSON.parse(fs.readFileSync(FIXTURE, 'utf8'));
assert.ok(FIXTURE_DATA.purchase && FIXTURE_DATA.purchase.event === 'purchase', 'fixture must carry a real purchase entry');
assert.ok(FIXTURE_DATA.view_item && FIXTURE_DATA.view_item.event === 'view_item', 'fixture must carry a real view_item entry');

const PURCHASE_EVENT_CONFIG = {
    name: 'purchase', enabled: true, value: 0, currency: FIXTURE_DATA.purchase.currency,
    ads_label: 'LBL', meta_resolved: 'Purchase',
    send_to: { ga4: true, meta: true, google_ads: true }, triggers: [],
};
const VIEW_ITEM_EVENT_CONFIG = {
    name: 'view_item', enabled: true, value: 0, currency: FIXTURE_DATA.view_item.currency,
    send_to: { ga4: true, meta: false, google_ads: false }, triggers: [],
};

function boot({ url = 'https://example.org/', trackwpWoo = {}, dataLayerEnabled = true, localStorageFrom = null } = {}) {
    const sb = createSandbox({
        url,
        config: {
            consent: { restUrl: REST },
            trackwp: {
                restUrl: REST,
                googleAds: { conversionId: 'AW-1', labels: [] },
                events: [PURCHASE_EVENT_CONFIG, VIEW_ITEM_EVENT_CONFIG],
                dataLayer: {
                    enabled: dataLayerEnabled,
                    ga4Source: 'gtm',
                    ga4Enabled: true,
                    mpConfigured: false,
                },
                dedupMode: 'client_and_server',
                debugAllowed: false,
            },
        },
    });

    // Minimal K3 reader stand-in, same shape as consent.js writes.
    vm.runInContext(
        `window.trackwpConsentReader = { read: function () {
            var m = document.cookie.match(/(?:^|; )trackwp_consent=([^;]*)/);
            if (!m) return null;
            try { return JSON.parse(decodeURIComponent(m[1])); } catch (e) { return null; }
        } };`,
        sb.window
    );

    const trackwpJs = path.join(PLUGIN_ROOT, 'assets', 'js', 'trackwp.js');
    vm.runInContext(fs.readFileSync(trackwpJs, 'utf8'), sb.window, { filename: trackwpJs });

    // window.trackwpWoo must exist BEFORE woocommerce.js's IIFE runs: it is
    // read synchronously at load, and init() (which calls fireImmediate())
    // fires immediately too, since window.trackwp.sendEvent already exists.
    sb.window.trackwpWoo = {
        immediate: [],
        products: {},
        addToCart: false,
        currency: 'DKK',
        itemIdSource: 'product_id',
        includeTax: true,
        debugAllowed: false,
        ...trackwpWoo,
    };

    // A reload in the same browser: carry the previous render's localStorage
    // (written by woocommerce.js itself) over before this render runs.
    if (localStorageFrom) {
        for (const [k, v] of Object.entries(localStorageFrom)) {
            sb.window.localStorage.setItem(k, v);
        }
    }

    const wooJs = path.join(PLUGIN_ROOT, 'assets', 'js', 'woocommerce.js');
    vm.runInContext(fs.readFileSync(wooJs, 'utf8'), sb.window, { filename: wooJs });

    return sb;
}

function setConsent(sb, { statistics = false, marketing = false } = {}) {
    sb.window.document.cookie =
        'trackwp_consent=' + encodeURIComponent(JSON.stringify({ v: 1, statistics, marketing, necessary: true, ts: new Date().toISOString(), id: 'c1' })) + '; path=/';
}

const tick = (ms = 20) => new Promise((r) => setTimeout(r, ms));

function eventCalls(sb) {
    return sb.spies.fetch
        .filter(([u]) => String(u).includes('trackwp/v1/event'))
        .map(([u, init]) => ({ url: String(u), body: init && init.body ? JSON.parse(init.body) : null }));
}

// dataLayer pushes come in R/event/R triples; the middle entry per cycle is
// the actual event.
function pushedEvents(sb) {
    return sb.window.dataLayer.filter((e) => e && e.event);
}

// === D2: push before any consent choice, no POST ===

test('KC7/D2: with no consent choice, the dataLayer push happens but nothing is POSTed', async () => {
    const sb = boot({ trackwpWoo: { immediate: [FIXTURE_DATA.view_item] } });
    await tick();

    const pushed = pushedEvents(sb);
    assert.equal(pushed.length, 1);
    assert.equal(pushed[0].event, 'view_item');
    assert.equal(eventCalls(sb).length, 0, 'no POST before a consent choice exists');
});

// === Later accept: POST carries the route decided at push time, no re-push ===

test('KC7: accepting later sends the POST with the route decided at push time, and does not push again', async () => {
    const sb = boot({ trackwpWoo: { immediate: [FIXTURE_DATA.view_item] } });
    await tick();
    assert.equal(pushedEvents(sb).length, 1);
    const routeAtPush = sb.window.dataLayer[1].trackwp.ga4_route;
    const eventIdAtPush = sb.window.dataLayer[1].trackwp.event_id;

    setConsent(sb, { statistics: true, marketing: false });
    sb.window.dispatchEvent({ type: 'trackwp:consent_updated' });
    await tick();

    assert.equal(pushedEvents(sb).length, 1, 'no second push after accepting');
    const calls = eventCalls(sb);
    assert.equal(calls.length, 1, 'the POST happens once consent allows it');
    assert.equal(calls[0].body.ga4_route, routeAtPush);
    assert.equal(calls[0].body.event_id, eventIdAtPush, 'TR8: the id minted at push time is reused for the POST');
});

// === Rejection: push happens, never a POST ===

test('KC7/D2: rejecting consent still leaves the earlier push in place, and never POSTs', async () => {
    const sb = boot({ trackwpWoo: { immediate: [FIXTURE_DATA.view_item] } });
    await tick();
    assert.equal(pushedEvents(sb).length, 1);

    setConsent(sb, { statistics: false, marketing: false });
    sb.window.dispatchEvent({ type: 'trackwp:consent_updated' });
    await tick();

    assert.equal(pushedEvents(sb).length, 1, 'still exactly the one push from before the choice');
    assert.equal(eventCalls(sb).length, 0, 'a rejection never POSTs');
});

// === R before/after every push (D3), even for a shop event ===

test('KC7/D3: R is pushed before and after the shop event', async () => {
    const sb = boot({ trackwpWoo: { immediate: [FIXTURE_DATA.view_item] } });
    await tick();
    const dl = JSON.parse(JSON.stringify(sb.window.dataLayer));
    assert.equal(dl.length, 3, 'reset, event, reset');
    assert.deepEqual(dl[0], { ecommerce: null, user_data: null, trackwp: null });
    assert.deepEqual(dl[2], { ecommerce: null, user_data: null, trackwp: null });
});

// === purchase: TR3, server's event_id reused for the push and the POST ===

test('TR3/TR8: purchase reuses the SERVER-issued event_id for both the dataLayer push and the later POST', async () => {
    const sb = boot({ trackwpWoo: { immediate: [FIXTURE_DATA.purchase] } });
    await tick();

    const pushed = pushedEvents(sb);
    assert.equal(pushed.length, 1);
    assert.equal(pushed[0].event, 'purchase');
    assert.equal(pushed[0].trackwp.event_id, FIXTURE_DATA.purchase.event_id, "the pushed id is the server's, not a freshly minted one");
    assert.equal(pushed[0].ecommerce.transaction_id, FIXTURE_DATA.purchase.ecommerce.transaction_id);

    setConsent(sb, { statistics: true, marketing: true });
    sb.window.dispatchEvent({ type: 'trackwp:consent_updated' });
    await tick();

    const calls = eventCalls(sb);
    assert.equal(calls.length, 1);
    assert.equal(calls[0].body.event_id, FIXTURE_DATA.purchase.event_id);
    assert.equal(calls[0].body.order_ref, FIXTURE_DATA.purchase.order_ref);
});

// === D2: a reloaded "already sent" purchase is never pushed again ===

test('D2: a purchase already sent from this browser is not pushed to the dataLayer again on reload, only claimed server-side', async () => {
    const first = boot({ trackwpWoo: { immediate: [FIXTURE_DATA.purchase] } });
    setConsent(first, { statistics: true, marketing: true });
    first.window.dispatchEvent({ type: 'trackwp:consent_updated' });
    await tick();
    assert.equal(pushedEvents(first).length, 1, 'first render pushes the purchase once');
    const stored = first.window.localStorage.getItem('trackwp_woo_purchases');
    assert.ok(stored && stored.includes(String(FIXTURE_DATA.purchase.ecommerce.transaction_id)), 'first render remembers the order');

    const reload = boot({ trackwpWoo: { immediate: [FIXTURE_DATA.purchase] }, localStorageFrom: { trackwp_woo_purchases: stored } });
    setConsent(reload, { statistics: true, marketing: true });
    reload.window.dispatchEvent({ type: 'trackwp:consent_updated' });
    await tick();
    assert.equal(pushedEvents(reload).length, 0, 'D2: no second dataLayer purchase for the same order');
    const calls = eventCalls(reload);
    assert.equal(calls.length, 1, 'the server claim still gets its chance to answer duplicate');
    assert.equal(calls[0].body.event_id, FIXTURE_DATA.purchase.event_id);
});

// === M1 (reviewer-deep fix, 2026-09-29): rememberPurchase() must run only
// once send() has actually POSTed, never synchronously and never on a
// rejection -- otherwise a visitor who lands on the thank-you page without a
// consent choice, reloads, and only THEN accepts would be treated as
// "already sent" and the Ads/Pixel Purchase would never fire. ===

test('M1: no consent choice never writes the purchase to localStorage, on or off dataLayer', async () => {
    for (const dataLayerEnabled of [true, false]) {
        const sb = boot({ dataLayerEnabled, trackwpWoo: { immediate: [FIXTURE_DATA.purchase] } });
        await tick();
        assert.equal(
            sb.window.localStorage.getItem('trackwp_woo_purchases'),
            null,
            `dataLayerEnabled=${dataLayerEnabled}: nothing may be remembered before any consent choice`
        );
        assert.equal(eventCalls(sb).length, 0);
    }
});

test('M1: a reload before any consent choice, followed by acceptance, still fires the Pixel/Ads branch', async () => {
    // "page load 1": no consent yet. Nothing sent, nothing remembered --
    // this is exactly what test above already proves, repeated here as the
    // starting point for the reload.
    const first = boot({ dataLayerEnabled: false, trackwpWoo: { immediate: [FIXTURE_DATA.purchase] } });
    await tick();
    assert.equal(first.window.localStorage.getItem('trackwp_woo_purchases'), null);

    // "reload": a fresh script execution (own window/closures) that inherits
    // the SAME (still empty) localStorage, exactly like a real reload would.
    const reload = boot({
        dataLayerEnabled: false,
        trackwpWoo: { immediate: [FIXTURE_DATA.purchase] },
        localStorageFrom: jsonToEntries(first.window.localStorage),
    });
    await tick();
    assert.equal(reload.spies.gtag.length, 0, 'still no consent on the reload itself');
    assert.equal(reload.spies.fbq.length, 0);

    setConsent(reload, { statistics: true, marketing: true });
    reload.window.dispatchEvent({ type: 'trackwp:consent_updated' });
    await tick();

    assert.ok(
        reload.spies.gtag.some((a) => a[0] === 'event' && a[1] === 'conversion'),
        'the Ads conversion fires on the reload once consent is granted (the M1 bug suppressed this forever)'
    );
    assert.ok(
        reload.spies.fbq.some((a) => a[0] === 'track' && a[1] === 'Purchase'),
        'the Pixel Purchase fires too'
    );
});

function jsonToEntries(storage) {
    const out = {};
    for (let i = 0; i < storage.length; i++) {
        const key = storage.key(i);
        out[key] = storage.getItem(key);
    }
    return out;
}

// === TR8: a non-purchase event's minted event_id is reused, not regenerated ===

test('TR8: a freshly minted event_id for a non-purchase event is identical at push and at the later POST', async () => {
    const sb = boot({ trackwpWoo: { immediate: [FIXTURE_DATA.view_item] } });
    await tick();
    const eventIdAtPush = sb.window.dataLayer[1].trackwp.event_id;
    assert.match(eventIdAtPush, /^evt_[a-f0-9]{32}$/);

    setConsent(sb, { statistics: true, marketing: false });
    sb.window.dispatchEvent({ type: 'trackwp:consent_updated' });
    await tick();

    const calls = eventCalls(sb);
    assert.equal(calls[0].body.event_id, eventIdAtPush);
});

// === Push happens even when the proxy fetch itself fails ===

test('D2: the dataLayer push happens even when fetch rejects once consent is already granted', async () => {
    const sb = boot({ trackwpWoo: { immediate: [] } });
    setConsent(sb, { statistics: true, marketing: false });
    sb.window.fetch = () => Promise.reject(new Error('network down'));
    await tick();

    sb.window.trackwpWooInternals && true; // sanity: internals exposed
    sb.window.dispatchEvent({ type: 'trackwp:consent_updated' }); // no queued events, just proves the handshake does not throw
    await tick();
    assert.ok(true, 'no unhandled exception even with fetch failing');
});

// === Without the dataLayer layer active, nothing changes (KC9 territory) ===

test('with the dataLayer layer inactive, no push happens but the POST still works once consent allows it', async () => {
    const sb = boot({ dataLayerEnabled: false, trackwpWoo: { immediate: [FIXTURE_DATA.view_item] } });
    await tick();
    assert.equal(pushedEvents(sb).length, 0, 'pushDataLayer itself no-ops when the layer is off');

    setConsent(sb, { statistics: true, marketing: false });
    sb.window.dispatchEvent({ type: 'trackwp:consent_updated' });
    await tick();
    const calls = eventCalls(sb);
    assert.equal(calls.length, 1);
    assert.equal(calls[0].body.ga4_route, undefined, 'no ga4_route travels when the layer never decided one');
});
